server:
  port: 8080


jwt:
  key: cookieencodedwithbase32algorithmabracadabraineedmorecharactersinthiskey
  expiration_time: 3600000

codec:
  key: 32charactersareeasytomakeanduse!

spring:
  application:
    name: banksystem
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: banking
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    default-schema: banking
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        security: DEBUG
        web:
          servlet:
            DispatcherServlet: DEBUG